<?php

/**
 * @file
 * Contains hogwarts_forms.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;


function hogwarts_forms_form_alter(&$form, &$form_state, $form_id){
  $form['account']['mail']['#weight'] = -11;
  $form['account']['name']['#weight'] = -12;
}

function hogwarts_forms_node_insert($entity){
  $config = \Drupal::service('config.factory')->getEditable('hogwarts_forms.nodeinsertmessage');
  
  $messenger = \Drupal::messenger();
  $messenger->addMessage($config->get('hogwarts_forms.nodeinsertmessage'));
}